import React, { useState } from 'react';
import { Twitter, Linkedin, Instagram, Facebook, Heart, MessageCircle, Repeat, Share, MoreHorizontal, Banana, X, Sparkles } from 'lucide-react';

const PostPreview = ({ content, image, platform = 'twitter' }) => {
    const [activePlatform, setActivePlatform] = useState(platform);

    const currentDate = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

    return (
        <div className="flex flex-col h-full bg-[#1a1d24] border-l border-white/[0.08] p-8 flex items-center justify-center">

            <div className="w-full max-w-[420px] bg-[#2a2f3b]/60 backdrop-blur-3xl border border-white/[0.12] rounded-[28px] overflow-hidden shadow-2xl p-7 relative">
                {/* Close Button Mock */}
                <div className="absolute top-7 right-7 text-white/50 hover:text-white cursor-pointer transition-colors">
                    <X size={22} />
                </div>

                {/* Header */}
                <div className="flex items-center gap-4 mb-5">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-yellow-400/20 to-purple-600/20 border border-white/10 flex items-center justify-center relative overflow-hidden group">
                        <div className="absolute inset-0 bg-gradient-to-br from-yellow-400 to-purple-600 opacity-30 group-hover:opacity-50 transition-opacity" />
                        <Banana className="text-yellow-400 relative z-10" size={22} />
                    </div>
                    <div>
                        <div className="flex items-center gap-1">
                            <span className="font-bold text-white text-[16px]">NanoBananaAI</span>
                        </div>
                        <div className="text-white/40 text-[14px]">@NanoBananaAI</div>
                    </div>
                </div>

                {/* Content */}
                <div className="mb-5">
                    <p className="text-white/85 text-[15px] leading-[1.6] whitespace-pre-wrap">
                        {content || "Professional AI powered Social Media newswtomers, most, aswerating and lnutiness: eneoditate with premium glass & light effects."}
                    </p>
                    {content && <p className="text-[#60a5fa] mt-3 font-medium text-[15px]">#NanoBananaAI</p>}
                </div>

                {/* Image */}
                {image && (
                    <div className="rounded-[20px] overflow-hidden mb-5 border border-white/[0.15] shadow-xl relative group">
                        <img src={image} alt="Post media" className="w-full h-auto object-cover" />
                        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-4">
                            <span className="text-white/80 text-xs font-medium flex items-center gap-2">
                                <Sparkles size={12} className="text-yellow-400" /> Generated by Nano Banana Pro
                            </span>
                        </div>
                    </div>
                )}

                {/* Footer Metadata */}
                <div className="text-white/35 text-[13px] mb-4 border-b border-white/[0.06] pb-4">
                    7:00 AM · {currentDate}
                </div>

                {/* Action Icons */}
                <div className="flex items-center justify-between text-white/35 px-1">
                    <MessageCircle size={20} className="hover:text-blue-400 transition-colors cursor-pointer" />
                    <Repeat size={20} className="hover:text-green-400 transition-colors cursor-pointer" />
                    <Heart size={20} className="hover:text-pink-500 transition-colors cursor-pointer" />
                    <div className="w-5 h-5 border border-white/20 rounded-sm flex items-center justify-center hover:bg-white/5 cursor-pointer transition-colors">
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path>
                        </svg>
                    </div>
                    <Share size={20} className="hover:text-blue-400 transition-colors cursor-pointer" />
                </div>
            </div>
        </div>
    );
};

export default PostPreview;
