import React from 'react';
import { Twitter, Linkedin, Instagram, Facebook, Heart, MessageCircle, Repeat, Share, MoreHorizontal, Banana, X, Sparkles, ThumbsUp, Send as SendIcon, Bookmark } from 'lucide-react';

const PostPreview = ({ content, image, platform = 'twitter' }) => {
    const currentDate = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

    const renderTwitterPreview = () => (
        <div className="w-full max-w-[420px] bg-[#2a2f3b]/60 backdrop-blur-3xl border border-white/[0.12] rounded-[28px] overflow-hidden shadow-2xl p-7 relative">
            {/* Header */}
            <div className="flex items-center gap-4 mb-5">
                <div className="w-12 h-12 rounded-full bg-gradient-to-br from-yellow-400/20 to-purple-600/20 border border-white/10 flex items-center justify-center relative overflow-hidden group">
                    <div className="absolute inset-0 bg-gradient-to-br from-yellow-400 to-purple-600 opacity-30 group-hover:opacity-50 transition-opacity" />
                    <Banana className="text-yellow-400 relative z-10" size={22} />
                </div>
                <div>
                    <div className="flex items-center gap-1">
                        <span className="font-bold text-white text-[16px]">NanoBananaAI</span>
                        <Twitter size={14} className="text-blue-400 ml-1" />
                    </div>
                    <div className="text-white/40 text-[14px]">@NanoBananaAI</div>
                </div>
            </div>

            {/* Content */}
            <div className="mb-5">
                <p className="text-white/85 text-[15px] leading-[1.6] whitespace-pre-wrap">
                    {content || "Draft your tweet to see how it looks..."}
                </p>
                {content && <p className="text-[#60a5fa] mt-3 font-medium text-[15px]">#NanoBananaAI</p>}
            </div>

            {/* Image */}
            {image && (
                <div className="rounded-[20px] overflow-hidden mb-5 border border-white/[0.15] shadow-xl relative group">
                    <img src={image} alt="Post media" className="w-full h-auto object-cover" />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-4">
                        <span className="text-white/80 text-xs font-medium flex items-center gap-2">
                            <Sparkles size={12} className="text-yellow-400" /> Generated by Nano Banana Pro
                        </span>
                    </div>
                </div>
            )}

            {/* Footer Metadata */}
            <div className="text-white/35 text-[13px] mb-4 border-b border-white/[0.06] pb-4">
                7:00 AM · {currentDate}
            </div>

            {/* Action Icons */}
            <div className="flex items-center justify-between text-white/35 px-1">
                <MessageCircle size={20} className="hover:text-blue-400 transition-colors cursor-pointer" />
                <Repeat size={20} className="hover:text-green-400 transition-colors cursor-pointer" />
                <Heart size={20} className="hover:text-pink-500 transition-colors cursor-pointer" />
                <Share size={20} className="hover:text-blue-400 transition-colors cursor-pointer" />
            </div>
        </div>
    );

    const renderLinkedInPreview = () => (
        <div className="w-full max-w-[480px] bg-white rounded-lg overflow-hidden shadow-xl font-sans">
            {/* Header */}
            <div className="p-4 flex items-start gap-3">
                <div className="w-12 h-12 rounded-full bg-gray-200 flex items-center justify-center overflow-hidden">
                    <Banana className="text-gray-600" size={24} />
                </div>
                <div>
                    <div className="flex items-center gap-1">
                        <span className="font-bold text-gray-900 text-sm">NanoBananaAI</span>
                        <span className="text-gray-500 text-xs">• 1st</span>
                    </div>
                    <div className="text-gray-500 text-xs">AI Innovation & Social Media Automation</div>
                    <div className="text-gray-500 text-xs flex items-center gap-1">
                        <span>1h • </span> <span className="bg-gray-400 rounded-full p-[1px]"><Linkedin size={8} className="text-white" fill="white" /></span>
                    </div>
                </div>
            </div>

            {/* Content */}
            <div className="px-4 pb-2">
                <p className="text-gray-800 text-sm whitespace-pre-wrap leading-relaxed">
                    {content || "Draft your LinkedIn post to see how it looks..."}
                </p>
            </div>

            {/* Image */}
            {image && (
                <div className="w-full">
                    <img src={image} alt="Post media" className="w-full h-auto object-cover" />
                </div>
            )}

            {/* Footer Actions */}
            <div className="px-4 py-2 border-t border-gray-100 flex items-center justify-between">
                <div className="flex items-center gap-1 text-gray-500 hover:bg-gray-100 px-2 py-3 rounded cursor-pointer transition-colors">
                    <ThumbsUp size={18} /> <span className="text-sm font-medium">Like</span>
                </div>
                <div className="flex items-center gap-1 text-gray-500 hover:bg-gray-100 px-2 py-3 rounded cursor-pointer transition-colors">
                    <MessageCircle size={18} /> <span className="text-sm font-medium">Comment</span>
                </div>
                <div className="flex items-center gap-1 text-gray-500 hover:bg-gray-100 px-2 py-3 rounded cursor-pointer transition-colors">
                    <Repeat size={18} /> <span className="text-sm font-medium">Repost</span>
                </div>
                <div className="flex items-center gap-1 text-gray-500 hover:bg-gray-100 px-2 py-3 rounded cursor-pointer transition-colors">
                    <SendIcon size={18} /> <span className="text-sm font-medium">Send</span>
                </div>
            </div>
        </div>
    );

    const renderInstagramPreview = () => (
        <div className="w-full max-w-[380px] bg-black border border-gray-800 rounded-xl overflow-hidden shadow-2xl text-white font-sans">
            {/* Header */}
            <div className="p-3 flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-yellow-400 to-purple-600 p-[2px]">
                        <div className="w-full h-full rounded-full bg-black flex items-center justify-center">
                            <Banana size={16} className="text-white" />
                        </div>
                    </div>
                    <span className="text-sm font-semibold">nanobanana.ai</span>
                </div>
                <MoreHorizontal size={20} />
            </div>

            {/* Image */}
            <div className="w-full aspect-square bg-gray-900 flex items-center justify-center overflow-hidden">
                {image ? (
                    <img src={image} alt="Post media" className="w-full h-full object-cover" />
                ) : (
                    <div className="text-gray-600 text-sm">Image Preview</div>
                )}
            </div>

            {/* Actions */}
            <div className="p-3">
                <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-4">
                        <Heart size={24} className="hover:text-red-500 cursor-pointer" />
                        <MessageCircle size={24} className="-rotate-90" />
                        <SendIcon size={24} />
                    </div>
                    <Bookmark size={24} />
                </div>
                <div className="text-sm font-semibold mb-2">1,234 likes</div>
                <div className="text-sm">
                    <span className="font-semibold mr-2">nanobanana.ai</span>
                    <span className="text-gray-100 whitespace-pre-wrap">{content || "Draft your caption..."}</span>
                </div>
                <div className="text-gray-500 text-xs mt-2 uppercase">2 hours ago</div>
            </div>
        </div>
    );

    return (
        <div className="flex flex-col h-full bg-[#1a1d24] border-l border-white/[0.08] p-8 flex items-center justify-center">
            {platform === 'twitter' && renderTwitterPreview()}
            {platform === 'linkedin' && renderLinkedInPreview()}
            {platform === 'instagram' && renderInstagramPreview()}
        </div>
    );
};

export default PostPreview;
